//const https = require('https');
const got = require("got");
const fs = require('fs');
const JSONL = require('json-literal');
const jsBeautify = require('js-beautify').js;

const urls = {
    '520': 'https://itch.io/bundle/520/games.json',
    '902': 'https://itch.io/bundle/902/games.json',
    '1316': 'https://itch.io/bundle/1316/games.json',
};

async function doStuff() {
    const games = {
        games: [],
        bundles: {
            "520": {
                id: "520",
                name: "Bundle for Racial Justice and Equality",
                url: "https://itch.io/b/520/bundle-for-racial-justice-and-equality",
                abbr: "RJE",
                color: "#808000",
            },
            "902": {
                id: "902",
                name: "Indie bundle for Palestinian Aid",
                url: "https://itch.io/b/902/indie-bundle-for-palestinian-aid",
                abbr: "PA",
                color: "#008000",
            },
            "1316": {
                id: "1316",
                name: "Bundle for Ukraine",
                url: "https://itch.io/b/1316/bundle-for-ukraine",
                abbr: "UA",
                color: "#0000cc",
            }
        }
    };
    let attribution = "// This file is auto-generated by update.js!\r\n";

    for(const bundle_id of Object.keys(urls)) {
        attribution += `// Sourced from ${urls[bundle_id]}\r\n`;

        let json = await got(urls[bundle_id]).text();
        json = json.replace(decodeURIComponent("%e2%80%a8"), ''); // the source json has a weird character that breaks things

        const bundle = JSON.parse(json);
        bundle.games = bundle.games.map(g => {
            delete g.price;
            delete g.bundle_game;
            g.bundles = [bundle_id];
            return g;
        })

        for(const game of bundle.games) {
            let existing = games.games.filter((g) => g.id === game.id);

            if(existing.length > 1) {
                console.error("Warning, multiple games exist for id " + game.id);
            }

            if(existing.length) {
                existing[0].bundles.push(bundle_id);
            }
            else {
                games.games.push(game);
            }
        }
    }

    json = JSONL.stringify(games, null, 2);
    let js = `${attribution}\r\nconst games = ${json};\r\n\r\n export default games;`;
    js = jsBeautify(js, {
        indent_size: 4,
    });
    fs.writeFileSync('games.js', js);

    const bundleStats = Object.fromEntries(Object.keys(urls).map(u => [u, 0]));
    const bundleExclusives = Object.fromEntries(Object.keys(urls).map(u => [u, 0]));

    for(const game of games.games) {
        for(const b of game.bundles) {
            bundleStats[b] += 1;
        }
        if(game.bundles.length === 1) {
            bundleExclusives[game.bundles[0]] += 1;
        }
    }

    for(const b of Object.keys(urls)) {
        console.log("Games in", games.bundles[b].name, ":", bundleStats[b], ", exclusive:", bundleExclusives[b]);
    }
}

doStuff().then(() => {
    console.log("Done");
}).catch((e) => {
    console.error(e);
})